<?php

namespace Database\Seeders;

use App\Models\Closure;
use App\Models\Department;
use App\Models\Idea;
use App\Models\User;
use Illuminate\Database\Seeder;

class IdeaTableSeeder extends Seeder
{
    public function run() 
    {
        $ideas = [
            [
                'title' => 'Campus-Wide Energy Retrofit Program',
                'content' => 'As energy costs continue to climb and climate change remains a pressing global issue, the Engineering Department proposes a transformative initiative to overhaul the university’s infrastructure for better energy efficiency. This program would involve retrofitting all major buildings with advanced sustainable materials, such as high-performance insulation, triple-glazed windows, and modern roofing designed to minimize heat loss. Additionally, we’d replace outdated lighting with energy-saving LED systems and upgrade HVAC units to smart, programmable models that adapt to occupancy patterns. The goal is to slash our campus carbon footprint by at least 30% within five years, setting a bold example for other institutions. Beyond the environmental benefits, this project would double as a hands-on learning opportunity—engineering students could participate in designing, testing, and monitoring these upgrades, gaining practical experience that complements their coursework. Faculty could also leverage the data from these systems for research on sustainable design, making the university a hub for innovation. Initial funding could come from a mix of grants, alumni donations, and reallocated maintenance budgets, with long-term savings offsetting the upfront costs. This isn’t just about fixing what’s broken; it’s about building a future-focused campus that reflects our values and prepares our students for the challenges ahead.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Engineering')->first()->id])->id,
            ],
            [
                'title' => 'Solar-Powered Engineering Complex',
                'content' => 'Picture a campus where the Engineering Department runs entirely on renewable energy—our team believes this vision can become reality with a solar-powered complex. We propose installing a network of high-efficiency solar panels across the rooftops of all engineering buildings, capable of generating enough electricity to power labs, lecture halls, workshops, and faculty offices. This isn’t just about cutting utility bills, though the savings would be substantial over time; it’s about creating an immersive educational environment. Students could monitor the panels’ performance through a dedicated dashboard, analyzing data on energy production, weather impacts, and system efficiency as part of their coursework. Faculty could integrate this setup into classes on renewable energy, offering real-world case studies that go beyond textbooks. The project would also include battery storage to ensure power availability during cloudy days or peak demand, showcasing the latest in energy management technology. To get started, we’d need to conduct a feasibility study—assessing roof conditions, local sunlight patterns, and installation costs—followed by a phased rollout to minimize disruption. Partnerships with green tech companies could provide discounted equipment, and student-led installation teams could reduce labor expenses while building their skills. This initiative would position our department as a leader in sustainable engineering, attracting eco-conscious students and faculty alike while contributing to the university’s broader sustainability goals.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Engineering')->first()->id])->id,
            ],
            [
                'title' => 'Next-Generation Smart Classrooms',
                'content' => 'The Engineering Department sees an opportunity to revolutionize how we teach and learn by transforming our lecture halls into next-generation smart classrooms. This initiative would involve outfitting key spaces with Internet of Things (IoT) devices—think motion sensors, smart thermostats, and energy-monitoring tools—linked to interactive touchscreens and augmented reality displays. Faculty could use these setups to demonstrate real-time concepts, like how building systems respond to occupancy or how energy flows through a circuit, making abstract theories tangible for students. Beyond the classroom, the data collected from these devices could feed into research projects, allowing us to study campus usage patterns and optimize resource allocation. For instance, imagine a lecture hall that adjusts lighting and temperature automatically based on the number of attendees, cutting waste without sacrificing comfort. Students would gain hands-on experience programming and maintaining these systems, preparing them for careers in smart infrastructure. To make this happen, we’d start with a pilot in one or two high-traffic rooms, partnering with tech firms for discounted hardware and tapping into grant funding for IoT education. The rollout would include training sessions for faculty to ensure they’re comfortable with the tools, plus a student tech crew to handle upkeep. This isn’t just an upgrade—it’s a leap forward that could inspire similar innovations across campus, enhancing both education and operational efficiency.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Engineering')->first()->id])->id,
            ],
            [
                'title' => 'Wind Energy Research and Training Hub',
                'content' => 'The Engineering Department proposes establishing a wind energy research and training hub right here on campus, starting with the installation of a modest wind turbine in an open area like the north quad. This isn’t just about generating a few kilowatts of power—it’s about creating a dynamic platform for education and innovation. The turbine would serve as a real-world testing ground where faculty could lead studies on blade aerodynamics, generator efficiency, and wind pattern analysis specific to our region, potentially publishing findings that contribute to the field. Students, meanwhile, would get practical training in everything from site assessment to turbine maintenance, skills that are increasingly in demand as renewable energy grows. We envision a setup that includes a small control room with monitoring equipment, allowing classes to observe live data and experiment with adjustments. To fund this, we could tap into state renewable energy grants and collaborate with industry partners who might donate components in exchange for research insights. The project would kick off with a site survey to ensure minimal environmental impact, followed by a student-involved construction phase to maximize learning opportunities. Over time, this hub could expand with additional turbines or even a wind-solar hybrid system, making our campus a showcase for sustainable tech. It’s a bold step that would elevate our reputation and give our community a direct stake in the clean energy future.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Engineering')->first()->id])->id,
            ],
            [
                'title' => 'Advanced Prototyping Center Expansion',
                'content' => 'The current 3D printing lab in the Engineering Department is a vital resource, but it’s bursting at the seams with demand from both faculty projects and student prototypes. We propose a major expansion of this facility into an Advanced Prototyping Center, equipped with additional industrial-grade 3D printers, laser cutters, and CNC machines to handle a wider range of materials and larger-scale designs. This upgrade would allow staff to develop complex models for university infrastructure improvements—like custom parts for lab equipment or sustainable building components—while giving students more room to experiment with their own innovations, from robotics to architectural mockups. Picture a space where a student team could design a new bike rack for campus, print it, test it, and refine it all in one semester. The center would also include a digital design suite with upgraded software and a materials library, fostering collaboration across disciplines. Funding could be secured through a mix of departmental budgets, alumni crowdfunding, and partnerships with tech companies eager to support STEM education. We’d start by renovating an underused storage area near the existing lab, ensuring the new space integrates seamlessly with current workflows. Staff training on the new equipment would be essential, as would a reservation system to manage access fairly. This expansion wouldn’t just fix our capacity issues—it would turbocharge our ability to innovate and support the university’s mission of hands-on learning and research excellence.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Engineering')->first()->id])->id,
            ],
            [
                'title' => 'Entrepreneurship Hub for Faculty and Students',
                'content' => 'The Business Department envisions a dedicated Entrepreneurship Hub on campus—a physical space where faculty and students can turn their ideas into viable startups. This wouldn’t just be a room with desks; it would be a fully equipped incubator with meeting spaces, prototyping tools, and access to a network of mentors from local industries and our alumni base. Faculty could use it to develop business models for university innovations—like a new app or a sustainable product—while students pitch their own ventures, from e-commerce platforms to social enterprises. The hub would offer workshops on market research, pitch development, and funding strategies, plus a small seed grant program to get projects off the ground. Imagine a professor collaborating with undergrads to launch a campus-based delivery service, or a student refining a business plan for a green tech startup with expert feedback. We’d fund this through a combination of departmental resources, private donations, and partnerships with regional business councils, starting with a pilot space in the business building before expanding based on demand. A key feature would be regular pitch nights, open to the campus community, to showcase progress and attract investors. This hub would bridge the gap between academic theory and real-world impact, boosting entrepreneurial skills and potentially generating revenue for the university through successful spin-offs.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Business')->first()->id])->id,
            ],
            [
                'title' => 'Comprehensive Financial Education Series',
                'content' => 'Financial literacy is a life skill too many lack, and the Business Department wants to change that with a year-round series of workshops for students and staff. This program would cover everything from crafting a personal budget to understanding student loan repayment, investing basics, and avoiding credit card debt traps. Picture a mix of in-person sessions—say, a Saturday morning seminar on retirement planning for staff—and online modules accessible anytime, like a 20-minute video on tax filing for students. Faculty with expertise in finance would lead the charge, tailoring content to different life stages: freshmen learning to stretch their meal plans, seniors preparing for post-grad expenses, and staff eyeing long-term savings goals. We’d also bring in guest speakers—local bankers, alumni financial advisors—to share real-world insights. The series could launch with a campus-wide “Money Matters” week, featuring booths, quizzes, and free consultations to drum up interest. Funding would come from a small reallocation of our outreach budget, supplemented by partnerships with financial literacy nonprofits offering free resources. Over time, we’d track participation and survey attendees to measure impact—did they save more? Pay off debt faster? This isn’t about quick fixes; it’s a sustained effort to empower our community with the tools for financial stability, enhancing well-being and reducing stress across campus.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Business')->first()->id])->id,
            ],
            [
                'title' => 'Green Purchasing Overhaul',
                'content' => 'The Business Department believes it’s time to align the university’s purchasing power with its sustainability goals, starting with a complete overhaul of our procurement policies. Currently, we buy supplies—paper, furniture, electronics—based on cost and convenience, but this often overlooks environmental impact. Our proposal is to prioritize vendors who offer eco-friendly products, like recycled paper or energy-efficient appliances, even if it means slightly higher upfront costs. We’d begin with a detailed audit of our supply chain, identifying where we can switch to greener options without disrupting operations—think bulk orders of biodegradable cleaning supplies or desks made from reclaimed wood. Faculty could involve students in the process, turning it into a case study on sustainable business practices: analyzing vendor certifications, calculating long-term savings from durable goods, and weighing trade-offs. The transition would be phased—starting with high-volume items like office supplies—supported by a task force to negotiate with suppliers and educate departments on the new guidelines. Funding could tap into existing budgets, offset by grants for sustainable initiatives, and the savings from energy-efficient purchases would accumulate over time. This isn’t just about checking a green box; it’s a chance to model responsible business leadership, reduce waste, and inspire other institutions to follow suit, all while giving our students practical exposure to ethical decision-making.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Business')->first()->id])->id,
            ],
            [
                'title' => 'Alumni Crowdfunding Platform',
                'content' => 'The Business Department proposes launching an Alumni Crowdfunding Platform to connect our graduates with campus projects needing financial support, creating a win-win for funding and engagement. This online portal would let faculty and staff pitch ideas—say, a new lecture series or lab equipment upgrades—complete with detailed budgets, timelines, and impact statements. Alumni could browse these proposals, donate to ones that resonate (maybe tied to their old department), and even offer mentorship or industry connections. Imagine a retired exec funding a student-led startup from the Entrepreneurship Hub, or a recent grad chipping in for a sustainability project they wish existed in their day. We’d build the platform with a user-friendly interface, integrated payment system, and regular updates on project progress to keep donors invested. The Business Department could oversee it, with students helping design the site and analyze donation trends as part of their studies. Startup costs would be modest—mostly web development and marketing—covered by a small grant or departmental funds, with a goal of breaking even through a tiny transaction fee once donations scale up. Success would hinge on a strong launch campaign, leveraging alumni networks and social media to spread the word. This platform wouldn’t just fill funding gaps; it’d strengthen our alumni community, give projects a fighting chance, and teach our students the art of crowdfunding in a real-world setting.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Business')->first()->id])->id,
            ],
            [
                'title' => 'University Efficiency Task Force',
                'content' => 'Wasteful spending is a silent drain on university resources, and the Business Department wants to tackle it head-on with a University Efficiency Task Force. This group—comprised of faculty, staff, and student reps—would conduct a top-to-bottom audit of our operations, from utility bills to office supplies, to pinpoint where money’s slipping through the cracks. Think overstocked printer paper sitting unused, or lights left on in empty buildings overnight—small issues that add up. The task force would spend a semester gathering data, interviewing departments, and benchmarking us against peer institutions, then deliver a report with actionable cuts, like consolidating software licenses or renegotiating vendor contracts. The savings—potentially hundreds of thousands annually—could be redirected to academic priorities: more scholarships, lab upgrades, or faculty hires. Students could join as interns, gaining experience in financial analysis and organizational management, while faculty bring expertise in cost-benefit analysis. We’d launch with a modest budget for travel and software, funded by reallocating existing resources, and aim for a self-sustaining model as savings kick in. The key is transparency—regular updates to the campus community would build trust and encourage buy-in. This isn’t about slashing budgets; it’s about working smarter, ensuring every dollar supports our core mission of education and research, and setting a precedent for fiscal responsibility that lasts.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::factory()->create(['department_id' => Department::where('name', 'Business')->first()->id])->id,
            ],
            [
                'title' => 'Interdisciplinary Creativity Lab',
                'content' => 'The Arts and Science Department envisions a groundbreaking Interdisciplinary Creativity Lab—a hybrid space where scientists and artists collaborate on projects that blur traditional boundaries. Imagine a renovated wing with lab benches alongside easels, microscopes next to sculpting tools, all designed to spark unexpected partnerships. Faculty could team up—a biologist and a painter studying plant patterns, or a physicist and a musician exploring sound waves—producing work that’s both research and exhibit. Students would benefit from courses taught in this space, like a seminar on bio-inspired design or a workshop on visualizing data through art, fostering skills in creative problem-solving. The lab would host public events—think gallery openings of staff-student creations or lectures on art-science intersections—to draw in the wider community. Funding could come from a mix of departmental budgets, arts grants, and donor campaigns targeting alumni in both fields, with a phased build-out starting in an underused classroom block. We’d need to outfit it with flexible furniture, basic lab gear, and art supplies, plus a small budget for visiting collaborators to kickstart projects. Success would hinge on a steering committee to manage bookings and ensure fair access across departments. This lab wouldn’t just enhance campus aesthetics or research output; it’d position us as a leader in interdisciplinary education, attracting curious minds and showcasing the power of blending two seemingly opposite worlds.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Arts and Science')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Arts and Science')->first()->id])->id,
            ],
            [
                'title' => 'University Open Research Portal',
                'content' => 'The Arts and Science Department proposes launching a University Open Research Portal—an online journal to showcase faculty work in both disciplines, freely accessible to the public. Too often, our research hides behind paywalls or gathers dust in archives; this platform would change that, publishing peer-reviewed articles, creative essays, and multimedia projects from staff across campus. A biologist might share a study on local ecosystems, while an art historian analyzes Renaissance techniques—each piece elevating our academic profile and sparking collaboration. Students could assist as editors or contributors, learning publication ropes and building resumes, while faculty gain visibility for grant applications or tenure reviews. We’d build it on an open-source platform, keeping costs low—mostly web hosting and a part-time coordinator—funded by a small departmental pool or library budget reallocation. The portal would launch with a call for submissions, aiming for quarterly issues, and include a comment section to foster discussion with readers worldwide. Promotion via social media and academic networks would drive traffic, with metrics tracking downloads to gauge impact. This isn’t just about sharing knowledge; it’s about democratizing it, strengthening ties with other institutions, and giving our community a louder voice in global conversations—something traditional journals can’t always offer.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Arts and Science')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Arts and Science')->first()->id])->id,
            ],
            [
                'title' => 'Native Habitat Restoration Project',
                'content' => 'The Arts and Science Department sees our campus as more than buildings—it’s an ecosystem waiting to thrive. We propose a Native Habitat Restoration Project, transforming underused green spaces into vibrant zones of local flora and fauna. This would mean planting native trees, shrubs, and wildflowers—species like oak, milkweed, and bluestem—chosen for their ecological benefits and resilience to our climate. Faculty could lead research on how these changes affect biodiversity, tracking pollinators or soil health, while students get muddy in planting days or monitor wildlife as part of ecology labs. Beyond science, art students could document the transformation through photography or installations, blending aesthetics with data. We’d start with a pilot plot—say, the east lawn—working with local conservation groups for seedlings and expertise, funded by a sustainability grant and small campus donations. Signage would educate passersby about each species’ role, turning the project into a living exhibit. Over years, we’d expand to other areas, like parking lot edges or dorm courtyards, measuring carbon sequestration to quantify our impact. Challenges like maintenance or invasive species would be learning opportunities, tackled by a student-staff crew. This isn’t just beautification; it’s a chance to heal our land, teach hands-on science, and inspire a campus culture that values nature as much as knowledge.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Arts and Science')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Arts and Science')->first()->id])->id,
            ],
            [
                'title' => 'Community Science Speaker Series',
                'content' => 'The Arts and Science Department wants to bring science out of the lab and into the campus spotlight with a Community Science Speaker Series. Picture monthly evening talks in the main auditorium—faculty presenting on urgent topics like climate shifts, exoplanet discoveries, or antibiotic resistance, tailored for a general audience. These wouldn’t be dry lectures; we’d aim for engaging formats—think live demos, Q&A sessions, or even debates between profs with opposing views. The goal is to demystify science, spark curiosity, and connect our community—students, staff, even local residents—around big ideas. We could kick off with a climate panel, tying into our sustainability efforts, then rotate through disciplines to keep it fresh. Funding would be minimal—mostly for mics, snacks, and promo—covered by departmental outreach funds or a ticket raffle for small prizes. Students could help organize, gaining event-planning skills, while faculty refine their public speaking, a win for professional growth. We’d record each talk for a YouTube channel, building an archive that extends our reach beyond campus. Success would depend on marketing—flyers, social media, maybe a tie-in with local schools—to pack the seats. This series wouldn’t just educate; it’d build a culture of inquiry, make our experts more accessible, and remind everyone that science isn’t just for labs—it’s for life.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Arts and Science')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Arts and Science')->first()->id])->id,
            ],
            [
                'title' => 'Staff Skill-Building Grant Program',
                'content' => 'The Human Resources Department recognizes that our staff are the backbone of this university, and we want to invest in their growth with a Staff Skill-Building Grant Program. This initiative would create a pool of funds—say, $50,000 annually—for employees to attend conferences, workshops, or certification courses relevant to their roles. A librarian could learn advanced cataloging tech, an admin could master project management, or a facilities worker could train in green building standards—each boosting their expertise and our campus capabilities. Applicants would submit a short proposal—why this training, how it helps their job—and a committee would award grants quarterly, prioritizing impact and fairness across departments. We’d fund it by reallocating a slice of the professional development budget, supplemented by donor gifts pitched as “staff excellence” investments. Post-training, recipients would share takeaways via a brown-bag lunch or memo, spreading the knowledge. Picture a maintenance tech teaching colleagues about energy-saving tricks learned at a seminar, or an HR rep streamlining hiring after a diversity workshop. The program would cap individual grants at $2,000 to stretch the pot, with a simple online portal for applications to keep it accessible. This isn’t just about skills; it’s about morale, retention, and showing staff we value their potential—benefits that ripple out to students and the whole university over time.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Human Resources')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Human Resources')->first()->id])->id,
            ],
            [
                'title' => 'Flexible Scheduling Pilot',
                'content' => 'Work-life balance isn’t just a buzzword—it’s a necessity, and the Human Resources Department proposes a Flexible Scheduling Pilot to prove it. This would let staff across departments opt into adjustable hours—say, starting at 7 a.m. to leave early, or compressing work into four 10-hour days—for a six-month trial. The idea is to test whether flexibility boosts productivity and satisfaction without disrupting operations. A facilities worker might prefer early shifts to beat traffic, while an academic advisor could stay late for evening student meetings. We’d start with a volunteer cohort—maybe 50 staff—tracking metrics like output, absenteeism, and self-reported stress via surveys. Departments would set core hours (e.g., 10 a.m. to 2 p.m.) to ensure overlap, with managers approving plans to avoid gaps. HR would provide guidelines and training to ease the shift, funded by existing resources—no big budget needed. Picture a registrar’s office humming efficiently with staggered schedules, or a lab tech happier with a longer weekend. Post-pilot, we’d analyze data and staff feedback to decide on a permanent policy, tweaking based on what works. Challenges like coverage would be met with cross-training or temp hires if needed. This pilot isn’t about chaos; it’s about trusting our team to deliver while living better, setting a model other universities might envy.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Human Resources')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Human Resources')->first()->id])->id,
            ],
            [
                'title' => 'Staff Wellness Mobile Platform',
                'content' => 'The Human Resources Department wants to put well-being in every staff member’s pocket with a custom Staff Wellness Mobile Platform. This app would be a one-stop shop for mental health resources—like guided meditations or crisis hotlines—plus fitness challenges (think step-count leaderboards) and daily tips on stress management or nutrition. Imagine a custodian unwinding with a 10-minute mindfulness session after a shift, or an admin joining a campus-wide “Walk to Work” contest. We’d develop it with input from staff via focus groups—ensuring it fits real needs—partnering with a tech firm for the build and a psychology prof for content vetting. Features could include a mood tracker, anonymous peer chat, and links to university counseling, all wrapped in an intuitive design. Funding would come from the wellness budget, maybe $20,000 upfront, with annual maintenance covered by small grants or HR funds. Launch would tie into a health fair, with tutorials to get everyone onboard. We’d measure success through usage stats and a post-launch survey—did it reduce burnout? Encourage exercise?—adjusting based on feedback. Security would be tight—encrypted data, opt-in sharing—to build trust. This isn’t a perk; it’s a lifeline, showing staff we care about their whole selves, not just their output, and fostering a healthier, happier workplace that benefits everyone.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Human Resources')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Human Resources')->first()->id])->id,
            ],
            [
                'title' => 'Annual Campus Health Fair',
                'content' => 'The Medicine Department proposes an Annual Campus Health Fair to bring preventive care straight to our community, leveraging our on-site medical facilities. Picture a day-long event in the student union—booths offering free blood pressure checks, cholesterol screenings, flu shots, and vision tests, all staffed by our faculty, med students, and local clinic partners. We’d add talks on sleep hygiene or stress reduction, plus a “know your numbers” station where attendees get a health snapshot to discuss with providers. This wouldn’t just serve staff and students—open it to families and locals to boost outreach. Funding would blend departmental resources with sponsorships from health orgs, keeping costs low—maybe $5,000 for supplies and promo. Students could earn practicum hours running stations, while faculty showcase expertise, like a doc explaining diabetes risks over coffee. Prep would take a small planning team, booking vendors and rallying volunteers months ahead, with marketing via posters, emails, and social media to pack the place. Success would show in attendance and follow-ups—did people seek care after? We’d tweak each year based on feedback, maybe adding dental checks or yoga demos. This fair isn’t just checkups; it’s a culture shift toward proactive health, strengthening our medical program’s impact and knitting our campus tighter with practical care.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Medicine')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Medicine')->first()->id])->id,
            ],
            [
                'title' => 'Cutting-Edge Medical Training Suite',
                'content' => 'The Medicine Department envisions a Cutting-Edge Medical Training Suite to elevate how we prepare students for real-world practice, right on campus. This would be a state-of-the-art facility—think high-fidelity mannequins that bleed and breathe, virtual reality stations for surgery sims, and exam rooms with one-way glass for peer review. Faculty could run scenarios like cardiac arrests or childbirth complications, giving students hands-on reps in a safe space before they hit clinics. Beyond undergrads, it’d serve continuing ed for staff docs and nurses, keeping skills sharp. We’d need a big space—maybe a renovated basement wing—outfitted with $500,000 in gear, funded by grants, alumni gifts, and a budget slice from Medicine. Construction would phase over a year to avoid disruption, starting with core sim tech and scaling up. Students could log hours here for certification, while faculty research how sim training impacts outcomes—data we could publish. A dedicated coordinator would manage bookings and maintenance, ensuring heavy use without chaos. Partnerships with med-tech firms might cut costs via donated demos, and we’d open it to regional providers for workshops, offsetting expenses with fees. Challenges like tech glitches or space limits would be met with a robust IT crew and flexible scheduling. This suite isn’t just gear; it’s a game-changer for our program, drawing top talent and cementing our rep as a hands-on medical leader.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Medicine')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Medicine')->first()->id])->id,
            ],
            [
                'title' => 'Healthy Living Campus Initiative',
                'content' => 'The Medicine Department wants to make health a campus-wide priority with a Healthy Living Campus Initiative, led by our faculty and students. This year-long campaign would flood the university with info and action on nutrition and exercise—think posters on balanced meals in dorms, a “move more” challenge with free fitness classes, and a website tracking progress. We’d kick off with a health expo—cooking demos, gym sign-ups, talks on heart health—then roll out monthly themes: January on hydration, February on sleep. Med students could design content, like a calorie guide for cafeteria eats, while faculty host Q&As on topics like obesity or mental wellness ties to diet. Funding would be lean—$10,000 from Medicine and wellness grants—covering materials, guest speakers, and prizes like water bottles or yoga mats to hook participants. We’d partner with dining services to tweak menus—more veggies, less fry oil—and facilities to open walking trails. Success would hinge on engagement—track class sign-ups, survey lifestyle shifts—and adjust based on what sticks. Picture a freshman swapping soda for water after a talk, or a prof joining a staff step challenge. This isn’t a lecture series; it’s a movement to shift habits, leverage our medical know-how, and build a campus where health isn’t an afterthought but a way of life.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Medicine')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Medicine')->first()->id])->id,
            ],
            [
                'title' => 'Campus Legal Support Line',
                'content' => 'The Law Department proposes a Campus Legal Support Line—a hotline where staff and students can get basic legal guidance from our faculty and upper-year law students. Imagine a stressed adjunct prof calling about a lease dispute, or a student needing help with a traffic ticket—our team would offer initial advice, explain options, and point them to resources, all free. It’d run weekday afternoons, staffed on rotation, with a simple call-in system and voicemail for off-hours. We’d cover common issues—contracts, landlord fights, small claims—stopping short of full representation to stay within scope. Funding would be minimal—phone setup and promo, maybe $2,000—pulled from Law’s outreach budget, with students earning clinic credit to keep labor free. Faculty could use cases (anonymized) in class, tying theory to practice, while building our community ties. Launch would need a splash—flyers, a website FAQ—to spread word, plus training for student reps on ethics and limits. Success would show in call volume and satisfaction surveys—did we save time, reduce stress?—with tweaks like evening hours if demand spikes. Challenges like complex cases would be met by clear disclaimers and referrals to local aid. This isn’t full lawyering; it’s a lifeline, boosting access to justice and showcasing our department’s real-world value.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Law')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Law')->first()->id])->id,
            ],
            [
                'title' => 'Mandatory Ethics Bootcamp',
                'content' => 'Integrity isn’t optional, and the Law Department wants to ensure every university employee knows it with a Mandatory Ethics Bootcamp. This would be a half-day workshop for all staff—admins to profs—run twice yearly by our faculty, diving into real-world dilemmas: conflicts of interest, data handling, student fairness. Picture a facilities worker debating gift rules, or a registrar tackling grade-change pressure—case studies would hit home, not just preach. We’d blend lectures with group discussions, ending with a pledge to uphold our code of conduct. Funding’s light—$5,000 for materials and catering—sourced from HR and Law budgets, with online follow-ups to cut repeat costs. Faculty would design it, tapping legal and ethical expertise, while students could assist for credit, prepping handouts or moderating. Rollout would stagger by department to avoid chaos, with a pilot for feedback—too long? Too dry?—before going full-scale. Success would mean fewer violations (tracked via HR reports) and staff confidence in tough calls. Challenges like resistance would be met with clear messaging: this isn’t punishment, it’s empowerment. Tie-ins with annual reviews could reinforce it. This bootcamp isn’t a checkbox; it’s a culture shift, rooting our operations in trust and accountability with Law leading the charge.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Law')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Law')->first()->id])->id,
            ],
            [
                'title' => 'University App Revamp',
                'content' => 'The Computer Science Department knows our current university app is clunky—slow, cluttered, and missing key features—so we propose a full University App Revamp. This would be a sleek, modern redesign—better navigation, real-time class schedules, campus maps with indoor routing, and push alerts for deadlines or emergencies. Imagine a student finding a free study room in seconds, or a prof checking lecture updates on the go. CS faculty would oversee, with students coding it as a capstone project—real stakes, real skills. We’d add bells like a lost-and-found tracker or dining menu integration, all based on user polls to nail what’s needed. Budget’s modest—$15,000 for servers, testing, and launch—funded by IT and CS, with open-source tools cutting costs. Rollout would start with a beta for volunteers, ironing out bugs before a campus-wide push, backed by tutorials and a help desk. Success hinges on downloads and crash reports—aim for 80% adoption in year one. Security’s priority—encrypted logins, no data leaks—with CS profs stress-testing it. Challenges like platform glitches would get quick patches via a student maintenance crew. This isn’t just an app; it’s a lifeline, streamlining campus life and showcasing our tech prowess to recruits and peers alike.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Computer Science')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Computer Science')->first()->id])->id,
            ],
            [
                'title' => 'Cybersecurity Crash Course Week',
                'content' => 'The Computer Science Department wants to arm our community against digital threats with a Cybersecurity Crash Course Week. This would be five days of workshops and simulations—phishing demos, password clinics, ransomware drills—led by our faculty and grad students for staff and students. Picture a clerk learning to spot scam emails, or a freshman locking down their laptop, all in hands-on sessions capped at 20 people for real interaction. We’d host it in CS labs, with a mobile “cyber van” hitting dorms and offices for pop-ups. Topics would hit basics—two-factor setup—then escalate to dark web myths or IoT risks, ending with a hackathon to test skills. Funding’s lean—$8,000 for gear, snacks, and promo—from CS and IT budgets, with free software from security firm pals. Students could earn a “Cyber Cert” badge, while staff get HR credit, boosting turnout. Launch ties to National Cybersecurity Month, with flyers and a teaser video to hype it. Success shows in quiz scores and fewer breaches—track IT tickets pre/post. Challenges like jargon would be cut with plain talk and cheat sheets. This isn’t techie fluff; it’s a campus shield, building savvy and resilience with CS leading the fight.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Computer Science')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Computer Science')->first()->id])->id,
            ],
            [
                'title' => 'Faculty Peer Teaching Program',
                'content' => 'The Education Department sees gold in our veteran educators and wants to share it with a Faculty Peer Teaching Program. This would pair seasoned profs with new or struggling staff—think a 20-year bio lecturer mentoring a rookie in chem—focusing on classroom craft: engaging lectures, fair grading, student rapport. It’d run a semester, with monthly meetups to swap lesson plans, observe classes, and debrief over coffee, plus a shared online folder for resources. No heavy hand—just voluntary matches based on style or need, coordinated by a small Education team. Funding’s light—$3,000 for stipends and snacks—from our budget, with a pilot of 10 pairs to test fit. Mentors get a nod in reviews, mentees gain confidence—picture a shaky adjunct nailing a tough topic after tips. We’d start with a call for sign-ups, matching via a quick survey, and end with a showcase—open classes or a panel on lessons learned. Success shows in teaching evals and retention—do newbies stick around? Challenges like time crunches get flex scheduling or virtual check-ins. This isn’t top-down; it’s peer-powered, spreading best practices and tightening our faculty web with Education at the helm.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Education')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Education')->first()->id])->id,
            ],
            [
                'title' => 'Virtual Teaching Resource Center',
                'content' => 'Online learning’s here to stay, and the Education Department wants staff ready with a Virtual Teaching Resource Center. This would be a one-stop digital hub—tutorials on Zoom tricks, guides for interactive quizzes, forums to troubleshoot Blackboard woes—open 24/7 for faculty. Picture a prof mastering breakout rooms after a 10-minute video, or swapping gamification ideas with peers online. We’d stock it with how-tos from our team, plus a live chat staffed by Education grad students for instant help—say, fixing a glitch mid-class. Funding’s modest—$12,000 for web build and a part-time coordinator—from our budget and an ed-tech grant. Students could contribute content for credit, keeping it fresh, while faculty suggest topics via a suggestion box. Launch would tie to a workshop day, with a demo and login help, pushed via email blasts. Success tracks via usage logs and a poll—did it cut prep time? Boost engagement?—with updates based on gripes. Security’s tight—password-protected, no student data—to ease privacy fears. Challenges like tech overwhelm get tiered resources—beginner to pro. This isn’t a Band-Aid; it’s a lifeline, leveling up our virtual game and keeping Education ahead in the digital shift.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Education')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Education')->first()->id])->id,
            ],
            [
                'title' => 'Inclusive Campus Dialogue Series',
                'content' => 'The Social Sciences Department wants to spark real talk with an Inclusive Campus Dialogue Series—quarterly forums on equity, diversity, and belonging, led by our faculty. Picture 90-minute sessions in the library hall: a sociologist unpacking microaggressions, a psych prof on mental health across cultures, open to all—students, staff, locals. We’d start with a panel—say, on gender inclusion—then break into small groups to hash out ideas, ending with action steps like better signage or bias training. Funding’s slim—$4,000 for mics, flyers, and coffee—from our outreach pot and a diversity grant. Students could co-facilitate for credit, building skills, while faculty tie talks to research—maybe a study on campus climate. Launch needs buzz—posters, a teaser vid, student org tie-ins—to fill seats. Success shows in attendance and follow-through—did ideas stick?—tracked via a quick exit survey. Challenges like tension get skilled moderators and ground rules—respect, no preaching. Tie-ins with HR or student life could amplify impact. This isn’t lip service; it’s a space to listen, learn, and shift our culture, with Social Sciences driving a more welcoming campus.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Social Sciences')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Social Sciences')->first()->id])->id,
            ],
            [
                'title' => 'Anonymous Well-Being Pulse Check',
                'content' => 'The Social Sciences Department proposes an Anonymous Well-Being Pulse Check—a yearly survey to gauge student and staff mental health and social needs, no names attached. Picture 20 questions online: stress levels, sense of belonging, access to support—done in 10 minutes, with a “comments” box for raw input. We’d run it each spring, analyzed by our faculty—psychologists, sociologists—to spot trends: Are dorm kids lonelier? Staff burned out? Results would guide services—more counselors, peer groups—without finger-pointing. Funding’s light—$3,000 for survey software and promo—from our budget and a wellness grant. Students could help craft questions for credit, ensuring relevance, while faculty publish findings (aggregated) for broader impact. Launch needs push—email blasts, class plugs—to hit 50% response; incentives like raffle tickets could nudge it. Success tracks via participation and action—did counseling calls rise?—with tweaks yearly. Privacy’s locked—encrypted, no IDs—to build trust. Challenges like apathy get short, punchy design and clear “why it matters” messaging. This isn’t a feel-good poll; it’s a data-driven push to catch struggles early and fix them, with Social Sciences turning numbers into care.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Social Sciences')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Social Sciences')->first()->id])->id,
            ],
            [
                'title' => 'Rotating Campus Art Exhibits',
                'content' => 'The Fine Arts Department wants to liven up our spaces with a Rotating Campus Art Exhibits program—commissioning staff and students to create pieces for public display, swapped out thrice yearly. Imagine a steel sculpture by a prof in the quad, student murals in the cafeteria—each with a plaque on its story. We’d call for proposals—sketches, concepts—judged by a faculty-student panel for impact and fit, with small stipends ($200-$500) for winners. Funding’s $10,000—materials, install, promo—from Fine Arts and a donor push framing it as “campus culture.” Artists get exposure—portfolio boosts, maybe sales—while campus gets soul. Start with a pilot—three spots like the library lawn—scaling if it clicks. Prep means a team to handle logistics—permits, mounting—plus a launch event with music and talks. Success shows in foot traffic and buzz—social media pics, student chatter—with a survey on vibe shift. Challenges like weatherproofing get durable media (metal, sealed paint) and maintenance plans. Tie-ins with classes could make it a project—sculpture 101’s next showpiece. This isn’t decor; it’s identity, turning blank walls into stories and Fine Arts into a campus heartbeat.',
                'is_anonymous' => false,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Fine Arts')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Fine Arts')->first()->id])->id,
            ],
            [
                'title' => 'Annual Staff Arts Festival',
                'content' => 'The Fine Arts Department proposes an Annual Staff Arts Festival—a day to spotlight our employees’ hidden talents, from music to theater to painting, and knit us closer. Picture a Saturday in spring: a prof’s jazz trio on an outdoor stage, an admin’s watercolors in a pop-up gallery, a facilities guy doing improv—all free, open to campus and town. We’d call for acts and art months ahead, curated by our faculty for quality and variety, with rehearsals or framing support from Fine Arts resources. Funding’s $7,000—stage, sound, promo—from our budget and a “community spirit” grant, keeping it simple—no big stars, just us. Staff get a mic to shine—boosting morale—while students could help run it for credit, learning event ropes. Launch needs hype—posters, a staff email blast—to rally performers and crowd. Success tracks via turnout and smiles—did folks linger?—with a post-event poll for next time. Weather’s a risk, so a rain site (gym?) and tents cover it. Tie-ins with local arts councils could grow it yearly. This isn’t a talent show; it’s a celebration, showing staff as whole people and Fine Arts as a spark for connection.',
                'is_anonymous' => true,
                'closure_id' => fn () => Closure::latest()->first()->id ?? Closure::factory()->create()->id,
                'user_id' => fn () => User::where('department_id', Department::where('name', 'Fine Arts')->first()->id)->first()->id ?? User::factory()->create(['department_id' => Department::where('name', 'Fine Arts')->first()->id])->id,
            ],
        ];

        foreach ($ideas as $idea) {
            Idea::create([
                'title' => $idea['title'],
                'content' => $idea['content'],
                'is_anonymous' => $idea['is_anonymous'],
                'closure_id' => $idea['closure_id'](),
                'user_id' => $idea['user_id'](),
            ]);
        }
    }
}